/**
 * Demo buyer demand pool — stands in for live retailer/processor RFQs.
 * Used so farmers can see ranked selling opportunities + net profit.
 */

import { isoDaysFromNow } from "./crops";

export type BuyerDemand = {
  id: string;
  buyerName: string;
  buyerType: "retailer" | "processor" | "hotel" | "kirana" | "exporter" | "fpo";
  category: string;
  cropKey: string;
  qty: number;
  unit: string;
  grade: string;
  maxPrice: number;
  location: string;
  lat: number;
  lng: number;
  distanceKm: number;
  deadline: string;
  urgency: "low" | "medium" | "high";
  notes: string;
};

/** Approximate farm hub near Chevella for route demos. */
export const FARM_HUB = {
  name: "Your farm · Chevella",
  lat: 17.312,
  lng: 78.138,
};

export const BUYER_DEMANDS: BuyerDemand[] = [
  {
    id: "dem-01",
    buyerName: "FreshMart Hyderabad",
    buyerType: "retailer",
    category: "Vegetables",
    cropKey: "tomato",
    qty: 200,
    unit: "kg",
    grade: "Grade A",
    maxPrice: 32,
    location: "Kukatpally, Hyderabad",
    lat: 17.494,
    lng: 78.399,
    distanceKm: 38,
    deadline: isoDaysFromNow(3),
    urgency: "high",
    notes: "Needs Grade A for retail shelves; prefers platform delivery.",
  },
  {
    id: "dem-02",
    buyerName: "Deccan Kitchen Group",
    buyerType: "hotel",
    category: "Vegetables",
    cropKey: "tomato",
    qty: 80,
    unit: "kg",
    grade: "Grade A",
    maxPrice: 30,
    location: "Banjara Hills, Hyderabad",
    lat: 17.415,
    lng: 78.435,
    distanceKm: 42,
    deadline: isoDaysFromNow(2),
    urgency: "high",
    notes: "Daily hotel kitchens — fast turnaround preferred.",
  },
  {
    id: "dem-03",
    buyerName: "Andhra Spice Processors",
    buyerType: "processor",
    category: "Spices",
    cropKey: "chilli",
    qty: 500,
    unit: "kg",
    grade: "Grade A",
    maxPrice: 170,
    location: "Guntur Industrial Estate",
    lat: 16.307,
    lng: 80.436,
    distanceKm: 270,
    deadline: isoDaysFromNow(10),
    urgency: "medium",
    notes: "Bulk processor; can take Grade A or Grade 1.",
  },
  {
    id: "dem-04",
    buyerName: "Godavari Rice Mills",
    buyerType: "processor",
    category: "Grains",
    cropKey: "paddy",
    qty: 2000,
    unit: "kg",
    grade: "Grade 1",
    maxPrice: 33,
    location: "Nizamabad, Telangana",
    lat: 18.672,
    lng: 78.094,
    distanceKm: 155,
    deadline: isoDaysFromNow(20),
    urgency: "low",
    notes: "Accepts Sona Masoori / Basmati lots above 1 tonne.",
  },
  {
    id: "dem-05",
    buyerName: "GreenLeaf Kirana Chain",
    buyerType: "kirana",
    category: "Vegetables",
    cropKey: "onion",
    qty: 400,
    unit: "kg",
    grade: "Grade A",
    maxPrice: 27,
    location: "Secunderabad",
    lat: 17.44,
    lng: 78.498,
    distanceKm: 48,
    deadline: isoDaysFromNow(5),
    urgency: "medium",
    notes: "Weekly restock for 12 kirana outlets.",
  },
  {
    id: "dem-06",
    buyerName: "Coastal Fruit Export Co-op",
    buyerType: "exporter",
    category: "Fruits",
    cropKey: "mango",
    qty: 800,
    unit: "kg",
    grade: "Grade 1",
    maxPrice: 95,
    location: "Vizag Port Yard",
    lat: 17.686,
    lng: 83.218,
    distanceKm: 620,
    deadline: isoDaysFromNow(7),
    urgency: "high",
    notes: "Export grading; pays premium for Grade 1 Banganapalli.",
  },
  {
    id: "dem-07",
    buyerName: "Medchal Fresh Collective",
    buyerType: "fpo",
    category: "Vegetables",
    cropKey: "tomato",
    qty: 150,
    unit: "kg",
    grade: "Grade A",
    maxPrice: 29,
    location: "Medchal, Telangana",
    lat: 17.629,
    lng: 78.481,
    distanceKm: 55,
    deadline: isoDaysFromNow(4),
    urgency: "medium",
    notes: "FPO aggregation hub — can split loads with nearby farms.",
  },
  {
    id: "dem-08",
    buyerName: "PulseCraft Foods",
    buyerType: "processor",
    category: "Pulses",
    cropKey: "moong",
    qty: 600,
    unit: "kg",
    grade: "Grade 1",
    maxPrice: 115,
    location: "Mahbubnagar",
    lat: 16.748,
    lng: 78.003,
    distanceKm: 95,
    deadline: isoDaysFromNow(28),
    urgency: "low",
    notes: "Dal mill intake; flexible on delivery window.",
  },
  {
    id: "dem-09",
    buyerName: "Urban Salad Co.",
    buyerType: "retailer",
    category: "Vegetables",
    cropKey: "carrot",
    qty: 120,
    unit: "kg",
    grade: "Grade A",
    maxPrice: 42,
    location: "Gachibowli, Hyderabad",
    lat: 17.44,
    lng: 78.348,
    distanceKm: 35,
    deadline: isoDaysFromNow(3),
    urgency: "high",
    notes: "Needs crisp Nantes carrots for meal kits.",
  },
  {
    id: "dem-10",
    buyerName: "Warangal Hotel Mart",
    buyerType: "hotel",
    category: "Vegetables",
    cropKey: "potato",
    qty: 300,
    unit: "kg",
    grade: "Grade A",
    maxPrice: 25,
    location: "Warangal",
    lat: 17.968,
    lng: 79.594,
    distanceKm: 145,
    deadline: isoDaysFromNow(6),
    urgency: "medium",
    notes: "Bulk kitchen stock; pickup from farm OK.",
  },
  {
    id: "dem-11",
    buyerName: "Hyderabad Mandi Traders",
    buyerType: "retailer",
    category: "Vegetables",
    cropKey: "tomato",
    qty: 500,
    unit: "kg",
    grade: "Grade A",
    maxPrice: 27,
    location: "Gudimalkapur Mandi",
    lat: 17.373,
    lng: 78.432,
    distanceKm: 32,
    deadline: isoDaysFromNow(1),
    urgency: "high",
    notes: "Volume buyer — lower price, fast clearance.",
  },
  {
    id: "dem-12",
    buyerName: "Erode Spice Hub",
    buyerType: "processor",
    category: "Spices",
    cropKey: "turmeric",
    qty: 700,
    unit: "kg",
    grade: "Grade A",
    maxPrice: 150,
    location: "Erode, Tamil Nadu",
    lat: 11.341,
    lng: 77.717,
    distanceKm: 510,
    deadline: isoDaysFromNow(35),
    urgency: "low",
    notes: "Finger turmeric preferred; long shelf window.",
  },
];
